export default {
    UPDATE_FECHA:"UPDATE_FECHA",
    GET_PROX_ESTRENOS:"GET_PROX_ESTRENOS", //acciones para proximos estrenos
    GET_PROX_ESTRENOS_FULFILLED:"GET_PROX_ESTRENOS_FULFILLED",//acciones para proximos estrenos
    GET_PROX_ESTRENOS_PENDING:"GET_PROX_ESTRENOS_PENDING",//acciones para proximos estrenos
    GET_PROX_ESTRENOS_REJECTED:"GET_PROX_ESTRENOS_REJECTED",//acciones para proximos estrenos
    GET_ESTRENOS:"GET_ESTRENOS",
    GET_ESTRENOS_PENDING:"GET_ESTRENOS_PENDING",
    GET_ESTRENOS_FULFILLED:"GET_ESTRENOS_FULFILLED",
    GET_ESTRENOS_REJECTED:"GET_ESTRENOS_REJECTED ",
    //acciones para creditos de pelicula
    GET_CREDITS:"GET_CREDITS",
    GET_CREDITS_PENDING:"GET_CREDITS_PENDING",
    GET_CREDITS_FULFILLED:"GET_CREDITS_FULFILLED",
    GET_CREDITS_REJECTED:"GET_CREDITS_REJECTED",
    //acciones para moviedetails o detalles de pelicula
    GET_DETAILS:"GET_DETAILS",
    GET_DETAILS_PENDING:"GET_DETAILS_PENDING",
    GET_DETAILS_FULFILLED:"GET_DETAILS_FULFILLED",
    GET_DETAILS_REJECTED:"GET_DETAILS_REJECTED",
    //acciones para compenente de busqueda 
    GET_SEARCH:"GET_SEARCH",
    GET_SEARCH_PENDING:"GET_SEARCH_PENDING",
    GET_SEARCH_FULFILLED:"GET_SEARCH_FULFILLED",
    GET_SEARCH_REJECTED:"GET_SEARCH_REJECTED",
    CLEAR_SEARCH:"CLEAR_SEARCH"
}